apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phonebook-frontend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phonebook-frontend
        stage: test
    spec:
      containers:
      - name: phonebook-frontend
        image: kube-registry:5000/phonebook-frontend:__IMG_VERSION__
        ports:
        - containerPort: 9292
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook-frontend
  namespace: default
  labels:
    app: phonebook-frontend
    stage: test
spec:
  selector:
    app: phonebook-frontend
  ports:
  - name: phonebook-frontend
    port: 80
    targetPort: 9292
    protocol: TCP
